[project]
name = "parts-walking-information-storage-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ulid-py>=1.1.0",
]
